### numpy


Câu 1 – 1D Array

Tạo một numpy array 1 chiều chứa các số: 1, 2, 3.

In mảng ra màn hình

In số chiều của mảng

In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(a.ndim)

[1 2 3]
1


Câu 2 – 2D Array

Tạo một numpy array 2 chiều từ danh sách:

[(1,2,3),
 (4,5,6)]


In mảng

In ndim, shape, size

In [4]:
b=np.array([[1,2,3], [4,5,6]])
print(b)
print(b.ndim)
print(b.shape)
print(b.size)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


Câu 3 – itemsize & dtype

Cho mảng:

a = np.array([1, 2, 3])


In kích thước 1 phần tử (byte)

In kiểu dữ liệu của mảng

In [5]:
a=np.array([1,2,3])
print(a.itemsize)
print(a.dtype)

8
int64


Câu 4 – So sánh bộ nhớ

Viết chương trình:

Tạo list từ 0 → 999

Tạo numpy array từ 0 → 999

In lượng bộ nhớ dùng cho list và numpy array

Comment: cái nào tiết kiệm hơn?

In [11]:
import sys
a=list(range(1000))
b=np.array(range(0,1000))
print(sys.getsizeof(a))
print(b.nbytes)
#Numpy array is more economical than list


8056
8000


Câu 5 – Reshape

Cho mảng:

a = np.array([(8,9,10),(11,12,13)])


In mảng ban đầu

Reshape thành (3,2)

In kết quả

In [12]:
a=np.array([(8,9,10),(11,12,13)])
print(a)
a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9 10]
 [11 12 13]]


Câu 6 – Slicing cơ bản

Cho mảng:

a = np.array([(1,2,3,4),
              (3,4,5,6)])


Lấy phần tử 3

Lấy toàn bộ phần tử ở cột thứ 3

Giải thích bằng comment từng dòng slicing

In [28]:
a = np.array([(1,2,3,4), (3,4,5,6)])
print(a[0,2])#3 is at 1st row and 3rd column so its index is 0 and 2
print(a[1,0])#3 is at 2nd row and 1st column so its index is 1 and 0
print(a[:,2])#3rd column means its index is 2, : to remove other positions



3
3
[3 5]


Câu 7 – linspace

Tạo một mảng gồm 10 số cách đều nhau trong khoảng [1, 3].

In [29]:
a=np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


Câu 8 – min, max, sum

Cho mảng:

a = np.array([1,2,3])


Tìm giá trị nhỏ nhất

Lớn nhất

Tổng các phần tử

In [36]:
a = np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

1
3
6


Câu 9 – axis

Cho mảng:

a = np.array([(1,2,3),
              (3,4,5)])


Tính tổng theo cột

Tính tổng theo hàng

Giải thích axis=0 và axis=1 bằng comment

In [37]:
a = np.array([(1,2,3), (3,4,5)])
print(a.sum(axis=0))#column
print(a.sum(axis=1))#row


[4 6 8]
[ 6 12]


Câu 10 – Các phép toán cơ bản

Cho:

x = np.array([(1,2,3),(3,4,5)])
y = np.array([(1,2,3),(3,4,5)])


Cộng

Trừ

Nhân

Chia

Dot product

In [40]:
x = np.array([(1,2,3),(3,4,5)])
y = np.array([(1,2,3),(3,4,5)])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
y=y.reshape(3,2)
print(np.dot(x,y))


[[ 2  4  6]
 [ 6  8 10]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[19 23]
 [35 43]]
